repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--config', 'actions/documentation/.markdownlint.json']
        files: \.md$

  - repo: https://github.com/stoplightio/spectral
    rev: v6.11.0
    hooks:
      - id: spectral-lint
        args: ['--ruleset', 'actions/api-spec/.spectral.yaml']
        files: \.(yaml|yml|json)$

  - repo: local
    hooks:
      - id: json-schema-validate
        name: Validate JSON Schema
        entry: ajv validate --spec=draft7 -s actions/categories/categories-schema.json -d categories.json
        language: node
        additional_dependencies: ['ajv-cli@5.0.0']
        files: categories\.json$
