openapi: 3.0.0
info:
  title: Pet Store API
  description: A simple API for managing a list of pets.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Local server
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        '200':
          description: A list of pets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: Create a pet
      operationId: createPet
      tags:
        - pets
      requestBody:
        description: The pet to create.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: Pet created successfully.
  /pets/{petId}:
    get:
      summary: Get a pet by ID
      operationId: getPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to retrieve.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A pet object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found.
    delete:
      summary: Delete a pet by ID
      operationId: deletePet
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to delete.
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Pet deleted successfully.
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
