name: Documentation and API Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'documentation/**/*.md'
      - 'openapi.yaml'
      - 'actions/action.yaml'
      - '.github/workflows/markdown-lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'documentation/**/*.md'
      - 'openapi.yaml'
      - 'actions/action.yaml'
  workflow_dispatch:

jobs:
  valid-lint-docs-and-api:
    name: Valid Lint Documentation and OpenAPI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Documentation and API Validation
        uses: ./actions
        with:
          documentation-directory: './valid-documentation'
          openapi-file: './valid-openapi.yaml'
          categories-file: './valid-categories.json'
          
      - name: Debug validation state
        if: always()
        shell: bash
        run: |
          echo " Debug Information:"
          echo "VALIDATION_FAILED: $VALIDATION_FAILED"
          echo "MARKDOWN_ERRORS: $MARKDOWN_ERRORS" 
          echo "OPENAPI_ERRORS: $OPENAPI_ERRORS"
          echo ""
          echo " File structure:"
          ls -la
          echo ""
          echo " Documentation directory:"
          ls -la documentation/ || echo "Documentation directory not found"
          echo ""
          echo " OpenAPI file:"
          ls -la openapi.yaml || echo "OpenAPI file not found"
          echo ""
          echo " Generated files:"
          ls -la *.md *.json *.yml 2>/dev/null || echo "No generated files found"
          
#      - name: Upload validation reports
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: validation-reports
#          path: |
#            .markdownlint.json
#            .spectral.yml
#            spectral-report.json
#            spectral-report.md
#            validation-errors.md
#          retention-days: 30

  invalid-lint-docs-and-api:
    name: Invalid Lint Documentation and OpenAPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Documentation and API Validation
        uses: ./actions
        with:
          documentation-directory: './invalid-documentation'
          openapi-file: './invalid-openapi.yaml'
          categories-file: './invalid-categories.json'

      - name: Debug validation state
        if: always()
        shell: bash
        run: |
          echo " Debug Information:"
          echo "VALIDATION_FAILED: $VALIDATION_FAILED"
          echo "MARKDOWN_ERRORS: $MARKDOWN_ERRORS" 
          echo "OPENAPI_ERRORS: $OPENAPI_ERRORS"
          echo ""
          echo " File structure:"
          ls -la
          echo ""
          echo " Documentation directory:"
          ls -la documentation/ || echo "Documentation directory not found"
          echo ""
          echo " OpenAPI file:"
          ls -la openapi.yaml || echo "OpenAPI file not found"
          echo ""
          echo " Generated files:"
          ls -la *.md *.json *.yml 2>/dev/null || echo "No generated files found"

#      - name: Upload validation reports
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: validation-reports
#          path: |
#            .markdownlint.json
#            .spectral.yml
#            spectral-report.json
#            spectral-report.md
#            validation-errors.md
#          retention-days: 30
